### ISSUE TITLE
cookie怎么获取？

### ISSUE THREAD

**Issue by zyh364267040** [flowerfalling/Auto_YouthStudy_Tianjin#1]
这个代码是只能刷次数的吗？cookie是在公众号上打开小程序的时候的那个cookie吗？

**Comment by flowerfalling** [comment]
只能刷学习排行里的学习次数

`--cookie`参数应填入当你访问 "http://admin.ddy.tjyun.com/zm/study" 时cookie中JSESSIONID字段的值

你可以通过`-o`参数来查看网站的返回报文

如果cookie错误或过期程序也会发出提示

**Comment by zyh364267040** [comment]
这样啊，是不是不能刷学习的人员数量，方便加个v吗，364267040@qq.com，方便的话发我邮箱，我加你。

**Comment by flowerfalling** [comment]
其实也研究过这个问题,还没有实践也不打算实践属实太麻烦了得搞模拟微信授权还有新人注册

**Comment by flowerfalling** [comment]
已查到关于代理的逻辑错误.你给我发个pr我改下就行,谢谢
